/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazeboindustries.sistemapizzaria.com;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Gazebo
 */
public class ActualRequests extends javax.swing.JFrame {
    SocketConnection connection;
    JSONObject jsonObj;
    String AllRequests;
    JSONObject AllRequestsJson;
    
   
    /**
     * Creates new form AppDesktopSistemaPizzaria
     */
    public ActualRequests() {
        initComponents();
        setLocationRelativeTo(null);
        
        jsonObj = new JSONObject();
             
        jsonObj.put("ID", "DesktopGetAllRequests");
        
         Timer timer = new Timer(1000, new ActionListenerLoop());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelLastRequest = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnFinishRequest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Imagebackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 850));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\SistemaPizzaria\\Images\\Logo.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 280, 170);

        PanelLastRequest.setBackground(new java.awt.Color(153, 0, 0));
        PanelLastRequest.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\SistemaPizzaria\\Images\\Imagem Cliente.jpg")); // NOI18N
        PanelLastRequest.add(jLabel2);
        jLabel2.setBounds(40, 100, 270, 190);

        getContentPane().add(PanelLastRequest);
        PanelLastRequest.setBounds(470, 60, 870, 670);

        btnFinishRequest.setBackground(new java.awt.Color(204, 204, 0));
        btnFinishRequest.setFont(new java.awt.Font("Impact", 3, 24)); // NOI18N
        btnFinishRequest.setText("CONCLUIR PEDIDO");
        btnFinishRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishRequestActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinishRequest);
        btnFinishRequest.setBounds(1050, 740, 280, 70);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 240, 370, 550);

        Imagebackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\SistemaPizzaria\\Images\\WallpaperDesktop2.jpg")); // NOI18N
        Imagebackground.setText("jLabel1");
        Imagebackground.setMaximumSize(new java.awt.Dimension(1440, 900));
        getContentPane().add(Imagebackground);
        Imagebackground.setBounds(-130, -20, 1570, 870);

        jMenu1.setText("Pedidos atuais");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Histórico de pedidos");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishRequestActionPerformed
        
    }//GEN-LAST:event_btnFinishRequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualRequests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagebackground;
    private javax.swing.JPanel PanelLastRequest;
    private javax.swing.JButton btnFinishRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    class ActionListenerLoop implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                connection = new SocketConnection("192.168.0.5",  3000);
                
                AllRequests = connection.SendMessage(String.valueOf(jsonObj));
                AllRequestsJson = new JSONObject(AllRequests);
                System.out.println(AllRequestsJson.get("1").toString());
                
                connection.Close();
                
            } catch (JSONException ex) {
                Logger.getLogger(ActualRequests.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ActualRequests.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }
    

}
