/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazeboindustries.sistemapizzaria.com;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Gazebo
 */
public class HistoryRequests extends javax.swing.JFrame {
    JSONObject jsonObj;
    SocketConnection connection;
    String AllRequests; 
    JSONObject AllRequestsJson;
    JSONObject FirstRequest;
    JPanel painelFundo;
    JScrollPane barraRolagem;
    JPanel RequestPanel;

    /**
     * Creates new form HistoryRequests
     */
    public HistoryRequests() {
        
        jsonObj = new JSONObject();
             
        jsonObj.put("ID", "DesktopGetAllRequests");
        
        painelFundo = new JPanel();     
       painelFundo.setBackground(new java.awt.Color(153, 0, 0));
       barraRolagem = new JScrollPane();
       barraRolagem.setViewportView(painelFundo);
       
        
        try {
            connection = new SocketConnection("192.168.0.5", 3000);
            
            AllRequests = connection.SendMessage(String.valueOf(jsonObj));
            
            System.out.println(AllRequests);
            AllRequestsJson = new JSONObject(AllRequests);
        } catch (IOException ex) {
            Logger.getLogger(HistoryRequests.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        painelFundo.setLayout(new GridLayout(AllRequestsJson.length() + 1, 1));
        JLabel[] PizzaLabel = new JLabel[AllRequestsJson.length() + 1];
        JLabel[] label = new JLabel[AllRequestsJson.length() + 1];
        JLabel[] PriceLabel = new JLabel[AllRequestsJson.length() + 1];
                
            for(int cont = 1; cont <=AllRequestsJson.length(); cont++){
                try{

                        label[cont] = new JLabel();
                        PizzaLabel[cont] = new JLabel();
                        PriceLabel[cont] = new JLabel();

                       System.out.println("TUDO CERTO");
                }catch(NullPointerException e){
                    System.out.println("ERRO");
                }
                }
        
                

        for(int i = 1; i <= AllRequestsJson.length(); i++){
            FirstRequest = (JSONObject) AllRequestsJson.get(Integer.toString(i));
            
            System.out.println(FirstRequest.toString());
            
            RequestPanel = new JPanel();
            
            RequestPanel.setBackground(new java.awt.Color(153, 0, 0));
            
            label[i].setText( FirstRequest.get("client").toString() + "                 ");
            label[i].setFont(new java.awt.Font("Postino Std", 1, 18));
            label[i].setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\SistemaPizzaria\\Images\\Imagem Cliente.jpg"));
            PizzaLabel[i].setText("<html>"+FirstRequest.get("pizzaType").toString()+ "<br/>" + FirstRequest.get("pizzaTaste1").toString() + " &emsp; &emsp; &emsp; &emsp; &emsp;"+"</html>" );
            PizzaLabel[i].setFont(new java.awt.Font("Postino Std", 1, 14));
            PizzaLabel[i].setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\SistemaPizzaria\\Images\\Imagem pizza.jpg"));
            PriceLabel[i].setText( " " +FirstRequest.get("totalPrice").toString());
            PriceLabel[i].setFont(new java.awt.Font("Postino Std", 1, 18));
            PriceLabel[i].setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\SistemaPizzaria\\Images\\Imagem Preço.png"));
            
            RequestPanel.add(label[i]);
            RequestPanel.add(PizzaLabel[i]);
            RequestPanel.add(PriceLabel[i]);
            
            painelFundo.add(RequestPanel);
            
             }
        
        getContentPane().add(barraRolagem);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        
        
        barraRolagem.setSize(1000, 720);
        
        initComponents();
        
        barraRolagem.setVisible(true);
        
        
        barraRolagem.setLocation(380,  30);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 850));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\SistemaPizzaria\\Images\\Logo.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 280, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gazebo\\Documents\\ProjetosGithub\\SistemaPizzaria\\Images\\WallpaperDesktop2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 850);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setText("Pedidos atuais");

        jMenuItem1.setText("Abrir Pedidos atuais");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ActualRequests().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryRequests().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
